spring:
  datasource:
    url: jdbc:h2:~/:testdb
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
